# Generated by Django 2.2.5 on 2019-09-27 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variants', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='GooseBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('keys', models.CharField(max_length=200)),
                ('price', models.FloatField(default=0)),
                ('manufacturer', models.CharField(max_length=100)),
                ('category', models.CharField(default='Разное', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Opponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rating', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OpponentGoose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_name', models.CharField(max_length=100)),
                ('url', models.URLField(max_length=1000)),
                ('goose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iron_parser.GooseBase')),
                ('opponent_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iron_parser.Opponent')),
            ],
        ),
        migrations.CreateModel(
            name='SubCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0)),
                ('check_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iron_parser.Check')),
                ('opponent_goose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iron_parser.OpponentGoose')),
            ],
        ),
        migrations.AddField(
            model_name='check',
            name='goose',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iron_parser.GooseBase'),
        ),
    ]
