# Generated by Django 2.2.5 on 2019-09-27 15:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iron_parser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 27, 18, 51, 53, 411523)),
        ),
    ]
