# Generated by Django 2.2.5 on 2019-10-03 11:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iron_parser', '0002_check_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='opponentgoose',
            name='available',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='check',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 3, 14, 4, 59, 376)),
        ),
    ]
