# Generated by Django 2.2.5 on 2019-10-06 12:18

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('iron_parser', '0003_auto_20191003_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='goosebase',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='check',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 6, 15, 18, 53, 471832)),
        ),
    ]
