# Generated by Django 2.2.5 on 2019-10-06 12:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iron_parser', '0004_auto_20191006_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 6, 15, 21, 50, 367813)),
        ),
        migrations.AlterField(
            model_name='goosebase',
            name='full_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='goosebase',
            name='manufacturer',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='goosebase',
            name='type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
