# Generated by Django 2.2.5 on 2019-10-09 11:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iron_parser', '0005_auto_20191006_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='goosebase',
            name='image',
            field=models.URLField(default='/static/image/no_image.png'),
        ),
        migrations.AlterField(
            model_name='check',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 9, 14, 57, 36, 556204)),
        ),
    ]
