# Generated by Django 2.2.5 on 2019-11-07 11:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iron_parser', '0007_auto_20191107_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='opponentgoose',
            name='img',
            field=models.URLField(default='/static/image/no_image.png'),
        ),
        migrations.AlterField(
            model_name='check',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 7, 14, 57, 0, 678258)),
        ),
    ]
