# Generated by Django 2.2.5 on 2019-11-07 12:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iron_parser', '0008_auto_20191107_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcheck',
            name='available',
            field=models.CharField(default='Не обновлено', max_length=100),
        ),
        migrations.AlterField(
            model_name='check',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 7, 15, 7, 2, 573036)),
        ),
    ]
