# Generated by Django 2.2.5 on 2019-11-15 18:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iron_parser', '0009_auto_20191107_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 15, 21, 53, 7, 489236)),
        ),
    ]
